version:  '3.8'

services:
  web:
    build:
      context:  .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image:  redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network 

networks:
  app_network:
    driver: bridge

volumes:
  redis_data: