# Generated by Django 5.1.5 on 2025-02-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cart_user_favoriteproduct_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
